
-- ----------------------------------------------------
-- 테이블 삭제
-- ----------------------------------------------------
DROP TABLE BOARD CASCADE CONSTRAINTS; -- BOARD 테이블 
DROP TABLE ADMIN CASCADE CONSTRAINTS; -- ADMIN 테이블
DROP TABLE NOTICE CASCADE CONSTRAINTS; -- NOTICE 테이블
DROP TABLE FAQ CASCADE CONSTRAINTS; -- FAQ 테이블
DROP TABLE QNA CASCADE CONSTRAINTS; -- QNA 테이블
DROP TABLE SUBWAY_USER CASCADE CONSTRAINTS; -- USER 테이블
DROP TABLE STATION CASCADE CONSTRAINTS; -- SATION 테이블

-- ----------------------------------------------------
-- CREATE 테이블
-- ----------------------------------------------------
-- STATION 테이블 (김지섭)
CREATE TABLE "STATION" (
   "STATION_NO"         NUMBER          PRIMARY KEY
   ,"STATION_NAME"      VARCHAR2(100)   NOT NULL
   ,"LINE_NO"           NUMBER          NOT NULL
   ,"TRANSFER_YN"       CHAR(1)         NOT NULL
   ,"EXIT_COUNT"        NUMBER          NOT NULL
   ,"WEEK_START_TIME"   CHAR(4)         NULL
   ,"WEEK_END_TIME"     CHAR(4)         NULL
   ,"HOL_START_TIME"    CHAR(4)         NULL
   ,"HOL_END_TIME"      CHAR(4)         NULL
   ,"TOILET_IO"         CHAR(1)         NULL
   ,"TOILET_FM"         CHAR(1)         NULL
   ,"TOILET_COUNT"      NUMBER          NULL
);

COMMENT ON COLUMN "STATION"."STATION_NO" IS '지하철역번호';
COMMENT ON COLUMN "STATION"."STATION_NAME" IS '역이름';
COMMENT ON COLUMN "STATION"."LINE_NO" IS '노선번호';
COMMENT ON COLUMN "STATION"."TRANSFER_YN" IS '환승여부';
COMMENT ON COLUMN "STATION"."EXIT_COUNT" IS '출구개수';
COMMENT ON COLUMN "STATION"."WEEK_START_TIME" IS '평일첫차시간';
COMMENT ON COLUMN "STATION"."WEEK_END_TIME" IS '평일막차시간';
COMMENT ON COLUMN "STATION"."HOL_START_TIME" IS '주말첫차시간';
COMMENT ON COLUMN "STATION"."HOL_END_TIME" IS '주말막차시간';
COMMENT ON COLUMN "STATION"."TOILET_IO" IS '화장실내외위치';
COMMENT ON COLUMN "STATION"."TOILET_FM" IS '남녀화장실구분';
COMMENT ON COLUMN "STATION"."TOILET_COUNT" IS '화장실개수';

-- 유저 테이블 (현지연)
CREATE TABLE SUBWAY_USER (
   USER_NO             NUMBER          PRIMARY KEY
    , ID               VARCHAR2(100)   NOT NULL UNIQUE
    , PWD              VARCHAR2(100)   NOT NULL
    , NICK             VARCHAR2(100)   NOT NULL
    , ENROLL_DATE      TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN           CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y' , 'N'))
    , PWDEDIT_DATE     TIMESTAMP
);
COMMENT ON COLUMN SUBWAY_USER.USER_NO IS '유저번호';
COMMENT ON COLUMN SUBWAY_USER.ID IS '유저 아이디';
COMMENT ON COLUMN SUBWAY_USER.PWD IS '유저 패스워드';
COMMENT ON COLUMN SUBWAY_USER.NICK IS '유저 닉네임';
COMMENT ON COLUMN SUBWAY_USER.ENROLL_DATE IS '가입일시';
COMMENT ON COLUMN SUBWAY_USER.DEL_YN IS '탈퇴여부';
COMMENT ON COLUMN SUBWAY_USER.PWDEDIT_DATE IS '마지막 수정일시';

DROP SEQUENCE SEQ_USER_NO;
CREATE SEQUENCE SEQ_USER_NO NOCYCLE NOCACHE;

-- BOARD, ADMIN 테이블 (조승범님)
CREATE TABLE ADMIN (
   ADMIN_NO            NUMBER          PRIMARY KEY
    ,ID                VARCHAR2(100)   NOT NULL UNIQUE
    ,PWD               VARCHAR2(100)   NOT NULL
    ,NICK              VARCHAR2(100)   NOT NULL
    ,DELETE_YN         CHAR(1)          DEFAULT 'N' CHECK(DELETE_YN IN('Y' , 'N'))
    ,PART_NAME         VARCHAR2(100)   NOT NULL
);
COMMENT ON COLUMN ADMIN.ADMIN_NO IS '관리자번호';
COMMENT ON COLUMN ADMIN.ID IS '관리자아이디';
COMMENT ON COLUMN ADMIN.PWD IS '관리자비밀번호';
COMMENT ON COLUMN ADMIN.NICK IS '관리자닉네임';
COMMENT ON COLUMN ADMIN.DELETE_YN IS '탈퇴여부';
COMMENT ON COLUMN ADMIN.PART_NAME IS '업무명';

CREATE TABLE BOARD (
   BOARD_NO               NUMBER              PRIMARY KEY
   ,STATION_NO            NUMBER              
   ,USER_NO               NUMBER              
   ,TITLE                 VARCHAR2(1000)      NOT NULL
   ,CONTENT               VARCHAR2(4000)      NOT NULL
   ,ENROLL_DATE           TIMESTAMP           DEFAULT SYSDATE
   ,MODIFY_DATE           TIMESTAMP
   ,INQUIRY               NUMBER              DEFAULT 0
   ,WRITER_NICK           VARCHAR2(100)      
   ,DELETE_YN             CHAR(1)             DEFAULT 'N' CHECK(DELETE_YN IN('Y' , 'N'))
);
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시판번호';
COMMENT ON COLUMN BOARD.STATION_NO IS '지하철역번호';
COMMENT ON COLUMN BOARD.USER_NO IS '유저번호';
COMMENT ON COLUMN BOARD.TITLE IS '게시판제목';
COMMENT ON COLUMN BOARD.CONTENT IS '게시판내용';
COMMENT ON COLUMN BOARD.ENROLL_DATE IS '작성일시';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '수정일시';
COMMENT ON COLUMN BOARD.INQUIRY IS '조회수';
COMMENT ON COLUMN BOARD.WRITER_NICK IS '작성자닉네임';
COMMENT ON COLUMN BOARD.DELETE_YN IS '삭제여부';

DROP SEQUENCE SEQ_ADMIN_NO;
DROP SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_ADMIN_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BOARD_NO NOCYCLE NOCACHE;

-- NOTICE, FAQ 테이블 (오의정님)
CREATE TABLE NOTICE(
    NOTICE_NO            NUMBER             PRIMARY KEY
    , STATION_NO         NUMBER             
    , ADMIN_NO           NUMBER             
    , POST_TIME          TIMESTAMP          DEFAULT SYSDATE
    , TITLE              VARCHAR2(4000)     NOT NULL
    , CONTENT            VARCHAR2(4000)     NOT NULL
    , INQUIRY            NUMBER             DEFAULT 0
    , DELETE_YN          CHAR(1)            DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))
    , MODIFY_DATE        TIMESTAMP         
);

CREATE TABLE FAQ(
    FAQ_NO               NUMBER             PRIMARY KEY
    , STATION_NO         NUMBER             
    , ADMIN_NO           NUMBER             
    , FAQ_TITLE          VARCHAR2(4000)     NOT NULL
    , CONTENT            VARCHAR2(4000)     NOT NULL
    , POST_TIME          TIMESTAMP          DEFAULT SYSDATE
    , DELETE_YN          CHAR(1)            DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))
    , MODIFY_DATE        TIMESTAMP
);

DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_FAQ_NO;

CREATE SEQUENCE SEQ_NOTICE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_FAQ_NO NOCYCLE NOCACHE;

-- QNA (이우철님)
CREATE TABLE QNA(
    QNA_NO               NUMBER             PRIMARY KEY
    , STATION_NO         NUMBER             
    , ADMIN_NO           NUMBER             
    , USER_NO            NUMBER             
    , POST_TIME          TIMESTAMP          DEFAULT SYSDATE
    , TITLE              VARCHAR2(100)      NOT NULL
    , CONTENT            VARCHAR2(1000)     NOT NULL
    , RE_TITLE           VARCHAR2(100)      NOT NULL
    , RE_CONTENT         VARCHAR2(1000)     NOT NULL
    , INQUIRY            NUMBER             DEFAULT 0
    , DELETE_YN          CHAR(1)            DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))
);

COMMENT ON COLUMN "QNA"."QNA_NO" IS '질의응답번호';
COMMENT ON COLUMN "QNA"."STATION_NO" IS '지하철역번호';
COMMENT ON COLUMN "QNA"."ADMIN_NO" IS '답변관리자번호';
COMMENT ON COLUMN "QNA"."USER_NO" IS '유저번호';
COMMENT ON COLUMN "QNA"."POST_TIME" IS '작성일시';
COMMENT ON COLUMN "QNA"."TITLE" IS '질의제목';
COMMENT ON COLUMN "QNA"."CONTENT" IS '질의내용';
COMMENT ON COLUMN "QNA"."RE_TITLE" IS '응답제목';
COMMENT ON COLUMN "QNA"."RE_CONTENT" IS '응답내용';
COMMENT ON COLUMN "QNA"."INQUIRY" IS '조회수';
COMMENT ON COLUMN "QNA"."DELETE_YN" IS '삭제여부';

DROP SEQUENCE SEQ_QNA_NO;
CREATE SEQUENCE SEQ_QNA_NO NOCYCLE NOCACHE;

-- ----------------------------------------------------
-- 외래키
-- ----------------------------------------------------



-- ----------------------------------------------------
-- 더미데이터
-- ----------------------------------------------------
-- SUBWAY_USER
INSERT INTO SUBWAY_USER(USER_NO, ID, PWD, NICK, ENROLL_DATE) VALUES(SEQ_USER_NO.NEXTVAL , 'USER01' , '1234' , '첫유저', SYSDATE);
INSERT INTO SUBWAY_USER(USER_NO, ID, PWD, NICK, ENROLL_DATE) VALUES(SEQ_USER_NO.NEXTVAL , 'USER02' , '1234' , '두번째유저', SYSDATE);

-- ADMIN
INSERT INTO ADMIN(ADMIN_NO, ID, PWD, NICK, PART_NAME) VALUES (1 ,'ADMIN01', '1234', 'STA', 'STATION');
INSERT INTO ADMIN(ADMIN_NO, ID, PWD, NICK, PART_NAME) VALUES (2, 'ADMIN02', '1234', 'SUB', 'SUBWAY');
INSERT INTO ADMIN(ADMIN_NO, ID, PWD, NICK, PART_NAME) VALUES (3, 'ADMIN03', '1234', 'FAQ', 'FAQ');
INSERT INTO ADMIN(ADMIN_NO, ID, PWD, NICK, PART_NAME) VALUES (4, 'ADMIN04', '1234', 'NOTI', 'NOTICE');
INSERT INTO ADMIN(ADMIN_NO, ID, PWD, NICK, PART_NAME) VALUES (5, 'ADMIN05', '1234', 'QNA', 'QNA');



